menosic/menosic/urls.py
from django.urls import include, path

from django.contrib import admin

app_name = 'menosic'
urlpatterns = [
    path('', include('music.urls', namespace='music')),

    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

menosic/music/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from music import views

app_name = 'music'
urlpatterns = [
    path('', login_required(views.HomePageView.as_view()), name='home'),
    path('guest/<int:pk>/', views.GuestPlaylistView.as_view(), name='guest_playlist'),
    path('playlist/', views.TemplateView.as_view(template_name='music/playlist.html'), name='playlist'),
    path('artist/<int:pk>/', views.ArtistDetailView.as_view(), name='artist_detail'),
    path('browse/<int:collection>/<path>/', views.BrowseView.as_view(), name='browse'),
    path('album/<int:pk>/', views.AlbumDetailView.as_view(), name='album_detail'),
    path('track/<int:pk>/', views.TrackDetailView.as_view(), name='track_detail'),
    path('last_played/', views.LastPlayedView.as_view(), name='last_played'),

    # playlist

    # tags
    path('play_album_track/<int:pk>/', views.PlayAlbumTrack.as_view(), name='play_album_track'),
    path('add_album/<int:pk>/', views.AddAlbumToPlaylist.as_view(), name='add_album'),
    path('add_track/<int:pk>/', views.AddTrackToPlaylist.as_view(), name='add_track'),

    # files
    path('play_album_files/<int:collection>/<path>/', views.PlayAlbumFiles.as_view(), name='play_album_files'),
    path('add_album_files/<int:collection>/<path>/', views.AddDirectoryToPlaylist.as_view(), name='add_album_files'),
    path('add_file/<int:collection>/<path>/', views.AddFileToPlaylist.as_view(), name='add_file'),

    path('edit_playlist_track/<int:pk>/<action>/', views.PlaylistTrack.as_view(), name='edit_playlist_track'),
    path('client/<int:pk>/', views.PlayerJSON.as_view(), name='client'),

    path('file/<int:pk>/', views.TrackView.as_view(), name='track'),
    path('file/<output>/<int:pk>/', views.TrackView.as_view(), name='track'),
    path('file/<output>/<int:collection>/<path>/', views.FileView.as_view(), name='file'),

    path('cover/<int:pk>/', views.CoverFileView.as_view(), name='cover'),
    path('album/random/<int:pk>/', views.RandomAlbumForArtistRedirect.as_view(), name='random_album'),
    path('album/random/', views.RandomAlbumRedirect.as_view(), name='random_album'),
    path('album/new/', views.NewAlbumList.as_view(), name="new_albums"),

    path('genre/<int:pk>/', views.GenreDetailView.as_view(), name='genre_detail'),
    path('country/<int:pk>/', views.CountryDetailView.as_view(), name='country_detail'),

    path('settings/', include('music.settings.urls', namespace='music_settings')),
    path('search/', views.SearchView.as_view(), name='search'),
]

menosic/menosic/templates/base.html
{% load static %}
<html>
<head>
    <title>Menosic</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}" />

    {% block head %}

    <script type="text/javascript" src="//code.jquery.com/jquery-2.2.0.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />

    <!-- Optional theme -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" />

    <!-- Latest compiled and minified JavaScript -->
    <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'menosic.css' %}" />

    <script type="text/javascript">
        // menosic variables
        var search_url = "{% url 'music:search' %}";

        // websocket variables
        var local_player = Math.random().toString(36).replace(/[^a-zA-Z0-9]+/g, '').substr(0, 10);
        var key = "{{ user.id }}";
        var playlist_url = "{% url 'music:playlist' %}";
        var playlist = {{ playlist.id }};
        var ws_url = "{{ ws_url }}";
        var ws;
    </script>
    <script type="text/javascript" src="{% static 'menosic.js' %}"></script>
    {% endblock head %}

</head>

<body>

{% block all %}

    <div id="container">
        <div id="header">
            <div>
                <h1><i class="glyphicon glyphicon-music"></i> Menosic</h1>
            </div>
            <div>
                <a class="to_content" href="{% url "music:settings:detail" %}"><i class="glyphicon glyphicon-wrench"></i></a>
                <label for="searchbox" class="glyphicon glyphicon-search"></label>
                <input id="searchbox" name="search" type="text" />
            </div>
        </div>
        <div id="big-part">
            <div id="left">

                <ul class="nav nav-tabs" role="tablist" id="left-tabs">
                    <li role="presentation" class="active"><a href="#artists" aria-controls="artists" role="tab" data-toggle="tab">Artists</a></li>
                    <li role="presentation"><a href="#genres" aria-controls="genres" role="tab" data-toggle="tab">Genres</a></li>

                </ul>

                <div class="tab-content" id="left-content" data-spy="scroll" data-target="#navigation">
                    <div role="tabpanel" class="tab-pane active" id="artists">

                        <div id="navigation" class="affix">
                          <ul class="nav">
                            <li class="bottom-buffer"><a class="external" href="{% url "music:random_album" %}"><i class="glyphicon glyphicon-random"></i></a></li>
                            <li class="bottom-buffer"><a class="external" href="{% url "music:new_albums" %}"><i class="glyphicon glyphicon-plus"></i></a></li>
                          {% for letter in letters %}
                            <li><a href="#{{ letter }}">{{ letter }}</a></li>
                          {% endfor %}
                          </ul>
                        </div>
                        <div id="artist-list">
                          <h2>Artists</h2>
                          <ul class="nav nav-sidebar">
                            {% for artist in artists %}
                            {% ifchanged artist.sortkeyname.0 %}
                                </ul>
                                    <span id="{{ artist.sortkeyname.0 }}">{{ artist.sortkeyname.0 }}</span>
                                <ul>
                            {% endifchanged %}

                            <li><a href="{{ artist.url }}">{{ artist.name }}</a></li>
                            {% endfor %}
                          </ul>
                        </div>

                    </div> <!-- artists -->

                    <div role="tabpanel" class="tab-pane" id="genres">
                        <h2>Genres</h2>
                        <ul>
                            {% for genre in genres %}
                            <li><a href="{{ genre.get_absolute_url }}">{{ genre.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div> <!-- genres -->
                    <div role="tabpanel" class="tab-pane" id="countries">
                        <h2>Countries</h2>
                        <ul>
                            {% for country in countries %}
                            <li><a href="{{ country.get_absolute_url }}">{{ country.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div> <!-- countries -->
                </div><!-- left-content -->

            </div> <!-- left -->
            <div id="middle-right">
                <div id="content-meta">
                    <div id="content">
                        {% include 'music/new_album_list.html' %}
                    </div>
                    <div id="meta">
                        <div id="last_played"></div>
                    </div>
                </div>
                <div id="player-container">
                    <div id="player-selector">
                        <label for="players">Play on:</label>
                        <select id="players"></select>
                    </div>
                    <audio controls id="player">
                        <source id="mp3" type="audio/mpeg" />
                        <source id="ogg" type="audio/ogg" />
                        Your browser does not support the audio tag!
                    </audio>
                    <div id="client-control">
                        <i id="client_pause" class="glyphicon glyphicon-pause"></i>
                        <i id="client_next" class="glyphicon glyphicon-fast-forward"></i>
                    </div>
                </div>
                <div id="playlist">
                    {% include 'music/playlist.html' %}
                </div>
            </div>
        </div>
    </div>

{% endblock all %}

</body>
</html>

menosic/menosic/templates/guest_playlist.html
{% extends 'base.html' %}

{% block head %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {{ block.super }}
{% endblock head %}

{% block all %}

    <div id="container">
        <div id="header">
            <div>
                <h1><i class="glyphicon glyphicon-music"></i> Menosic</h1>
            </div>
        </div>
        <div id="big-part">
            <div id="middle-right">
                <div id="content-meta">
                    <div id="playlist">
                        <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Artist</th>
                                <th>Album</th>
                                <th>Duration</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for pt in playlist.tracks %}
                            <tr id="{{ pt.identifier }}" {% if pt.identifier == current %}class="playing"{% endif %}>
                                <td><a class="to_player" mp3="{{ pt.track.get_mp3_url }}" ogg="{{ pt.track.get_ogg_url }}">{{ pt.track.title }}</a></td>
                                <td>{{ pt.track.artist }}</td>
                                <td>{{ pt.track.album.title }}</td>
                                <td>{{ pt.track.duration }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        </table>
                    </div>
                </div>
                <div id="player-container">
                    <audio controls id="player">
                        <source id="mp3" type="audio/mpeg" />
                        <source id="ogg" type="audio/ogg" />
                        Your browser does not support the audio tag!
                    </audio>
                    <div id="client-control">
                        <i id="client_pause" class="glyphicon glyphicon-pause"></i>
                        <i id="client_next" class="glyphicon glyphicon-fast-forward"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock all %}