menosic/menosic/urls.py
from django.urls import include, path

from django.contrib import admin

app_name = 'menosic'
urlpatterns = [
    path('', include('music.urls', namespace='music')),

    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

menosic/music/settings/urls.py
from django.urls import path
from . import views

app_name = 'settings'
urlpatterns = [
    path('', views.MusicSettingsView.as_view(), name="detail"),
]

menosic/music/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from music import views

app_name = 'music'
urlpatterns = [
    path('', login_required(views.HomePageView.as_view()), name='home'),
    path('guest/<int:pk>/', views.GuestPlaylistView.as_view(), name='guest_playlist'),
    path('playlist/', views.TemplateView.as_view(template_name='music/playlist.html'), name='playlist'),
    path('artist/<int:pk>/', views.ArtistDetailView.as_view(), name='artist_detail'),
    path('browse/<int:collection>/<path>/', views.BrowseView.as_view(), name='browse'),
    path('album/<int:pk>/', views.AlbumDetailView.as_view(), name='album_detail'),
    path('track/<int:pk>/', views.TrackDetailView.as_view(), name='track_detail'),
    path('last_played/', views.LastPlayedView.as_view(), name='last_played'),

    # playlist

    # tags
    path('play_album_track/<int:pk>/', views.PlayAlbumTrack.as_view(), name='play_album_track'),
    path('add_album/<int:pk>/', views.AddAlbumToPlaylist.as_view(), name='add_album'),
    path('add_track/<int:pk>/', views.AddTrackToPlaylist.as_view(), name='add_track'),

    # files
    path('play_album_files/<int:collection>/<path>/', views.PlayAlbumFiles.as_view(), name='play_album_files'),
    path('add_album_files/<int:collection>/<path>/', views.AddDirectoryToPlaylist.as_view(), name='add_album_files'),
    path('add_file/<int:collection>/<path>/', views.AddFileToPlaylist.as_view(), name='add_file'),

    path('edit_playlist_track/<int:pk>/<action>/', views.PlaylistTrack.as_view(), name='edit_playlist_track'),
    path('client/<int:pk>/', views.PlayerJSON.as_view(), name='client'),

    path('file/<int:pk>/', views.TrackView.as_view(), name='track'),
    path('file/<output>/<int:pk>/', views.TrackView.as_view(), name='track'),
    path('file/<output>/<int:collection>/<path>/', views.FileView.as_view(), name='file'),

    path('cover/<int:pk>/', views.CoverFileView.as_view(), name='cover'),
    path('album/random/<int:pk>/', views.RandomAlbumForArtistRedirect.as_view(), name='random_album'),
    path('album/random/', views.RandomAlbumRedirect.as_view(), name='random_album'),
    path('album/new/', views.NewAlbumList.as_view(), name="new_albums"),

    path('genre/<int:pk>/', views.GenreDetailView.as_view(), name='genre_detail'),
    path('country/<int:pk>/', views.CountryDetailView.as_view(), name='country_detail'),

    path('settings/', include('music.settings.urls', namespace='music_settings')),
    path('search/', views.SearchView.as_view(), name='search'),
]

menosic/music/models.py
import os
import json
import urllib.parse
import urllib.error
import urllib.request
import datetime
import importlib
import mimetypes
from collections import defaultdict
from django.contrib.auth.models import User
from django.conf import settings
from django.db import models
from django.utils import timezone
from music import helpers
from music.backend import files as files_backend

class Collection(models.Model):
    COLLECTION_BACKENDS = (
        ('T', 'Tags'),
        ('F', 'Files'),  # not yet implemented
        ('R', 'Remote'),  # not yet implemented
    )
    name = models.CharField(max_length=255, db_index=True)
    backend = models.CharField(max_length=1, choices=COLLECTION_BACKENDS)
    location = models.CharField(max_length=255)
    sendfile_location = models.CharField(max_length=255, null=True, blank=True)
    disabled = models.BooleanField(default=False)

    def scan(self, path=None):
        if path and path.startswith(self.location):
            path = path[len(self.location):]
        try:
            backend_module = self.get_backend_display().lower()
            module = 'music.backend.%s.scan' % backend_module
            backend = importlib.import_module(module)
            return backend.Scan(self, path=path)
        except ImportError:
            print("Don't know how to scan :(")


class Genre(models.Model):
    name = models.CharField(max_length=255, db_index=True)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('music:genre_detail', args=[self.pk])

    def artists(self):
        return self.artist_set.exclude(album=None)


class Country(models.Model):
    name = models.CharField(max_length=255, db_index=True)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('music:country_detail', args=[self.pk])


class Artist(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    sortname = models.CharField(max_length=255, db_index=True)
    genres = models.ManyToManyField(Genre)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True)
    path = models.CharField(max_length=255, db_index=True, null=True)
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)
    artists = models.ManyToManyField('music.Artist')

    musicbrainz_artistid = models.UUIDField(null=True)

    class Meta:
        ordering = ['sortname']
        unique_together = (
            ('collection', 'path'),
            ('collection', 'name', 'musicbrainz_artistid'),
        )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('music:artist_detail', args=[self.pk])

    def related_artists(self):
        return  Artist.objects.filter(track__artists=self).exclude(id=self.id).distinct() | \
                Artist.objects.filter(artists__artist=self).exclude(id=self.id).distinct() | \
                Artist.objects.filter(musicbrainz_artistid=self.musicbrainz_artistid, musicbrainz_artistid__isnull=False).exclude(id=self.id).distinct() | \
                self.artists.distinct() | self.artist_set.distinct()


    def related_albums(self):
        return Album.objects.filter(track__artists=self).exclude(artist=self).distinct() | \
               Album.objects.filter(artist__artists=self).exclude(artist=self).distinct()


class AlbumType(models.Model):
    name = models.CharField(max_length=255, db_index=True)


class AlbumStatus(models.Model):
    name = models.CharField(max_length=255, db_index=True)


class Label(models.Model):
    name = models.CharField(max_length=255, db_index=True)


class Album(models.Model):
    title = models.CharField(max_length=255, db_index=True)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    date = models.CharField(max_length=15, null=True, db_index=True)
    genres = models.ManyToManyField(Genre)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True)
    path = models.CharField(max_length=255, db_index=True, null=True)
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)

    labels = models.ManyToManyField(Label)
    albumtypes = models.ManyToManyField(AlbumType)
    albumstatus = models.ManyToManyField(AlbumStatus)

    musicbrainz_albumid = models.UUIDField(primary_key=False, null=True)
    musicbrainz_releasegroupid = models.UUIDField(primary_key=False, null=True)

    class Meta:
        ordering = ['date']
        unique_together = (
            ('collection', 'path'),
            ('collection', 'musicbrainz_albumid'))

    def __str__(self):
        return self.title

    @property
    def year(self):
        if self.date:
            return self.date[:4]
        else:
            return None

    @property
    def album_types(self):
        return [ at.name for at in self.albumtypes.all() if at.name != 'album' ]

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('music:album_detail', args=[self.pk])

    def cover(self, return_if_not_exists=False):
        if self.path:
            path = self.path
        else:
            try:
                first_track = self.track_set.all()[0]
            except IndexError:
                return None
            path = os.path.dirname(first_track.path)
            if os.path.basename(path).startswith('Disc'):
                path = os.path.dirname(path)

        c = os.path.join(path, 'cover.jpg')
        if os.path.isfile(c) or return_if_not_exists:
            return c

    def get_cover_url(self):
        from django.urls import reverse
        return reverse('music:cover', args=[self.pk])

    def _mbid_cover_download(self, mbid, cover):
        try:
            request = "http://coverartarchive.org/release/{mbid}/".format(mbid=mbid)
            response = urllib.request.urlopen(request)
            obj = json.loads(response.read().decode('utf-8'))
            url = obj['images'][0]['image']
            urllib.request.urlretrieve(url, cover)
            return True
        except (urllib.error.HTTPError, KeyError):
            return False


    def download_cover(self, override=False, search_lastfm=False):
        cover = self.cover(return_if_not_exists=True)

        if (cover and os.path.isfile(cover)) and not override:
            return 

        if not (self.musicbrainz_albumid and self._mbid_cover_download(self.musicbrainz_albumid, cover)) and search_lastfm:
            request = "http://ws.audioscrobbler.com/2.0/?method=album.getinfo&api_key={api_key}&artist={artist}&album={album}&format=json".format(
                    api_key = settings.LASTFM_API_KEY,
                    artist = urllib.parse.quote_plus(self.artist),
                    album = urllib.parse.quote_plus(self.title))

            try:
                response = urllib.request.urlopen(request)
                obj = json.loads(response.read().decode('utf-8'))
            except urllib.error.URLError:
                print("image not found on lastfm: {artist} - {album}".format(artist=self.artist, album=self.title))

            else:
                images = dict([ (item['size'], item['#text']) for item in obj['album']['image'] ])
                image_preference = ['mega', 'extralarge', 'large', 'medium', 'small']

                image_url = None
                for i in image_preference:
                    if i in images.keys():
                        image_url = images[i]
                        break

                if image_url:
                    try:
                        urllib.request.urlretrieve(image_url, cover)
                    except urllib.error.URLError:
                        print("error while downloading cover for {artist} - {album} on url: {url}".format(artist=self.artist, album=self.title, url=image_url))


class Track(models.Model):
    discnumber = models.PositiveIntegerField(null=True)
    tracknumber = models.PositiveIntegerField(null=True)
    title = models.CharField(max_length=255)
    album = models.ForeignKey(Album, on_delete=models.CASCADE, null=True)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, related_name='track_display_set')
    artists = models.ManyToManyField(Artist)
    length = models.PositiveIntegerField(null=True)
    bitrate = models.PositiveIntegerField(null=True)
    filetype = models.CharField(max_length=15, null=True)
    filesize = models.PositiveIntegerField(null=True)
    mtime = models.DateTimeField(null=True)
    path = models.CharField(max_length=255, db_index=True)
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)

    musicbrainz_trackid = models.UUIDField(primary_key=False, null=True)

    class Meta:
        ordering = ['discnumber', 'tracknumber']
        unique_together = (
            ('collection', 'path'),)

    def __str__(self):
        return self.title

    @property
    def full_path(self):
        return self.path

    @property
    def relative_path(self):
        if not self.full_path.startswith(self.collection.location):
            raise Exception('Something is wrong.. The file path is outside the collection path.')
        return self.full_path[len(self.collection.location):]

    @property
    def sendfile_location(self):
        return urllib.parse.quote("%s%s" % (self.collection.sendfile_location, self.relative_path), safe='/')

    @property
    def duration(self):
        return helpers.duration(self.length)

    @property
    def mimetype(self):
        mimetype, encoding = mimetypes.guess_type(self.path)
        return mimetype

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('music:track_detail', args=[self.pk])

    def get_mp3_url(self):
        from django.urls import reverse
        return reverse('music:track', args=['mp3', self.pk])

    def get_ogg_url(self):
        from django.urls import reverse

menosic/music/settings/models.py
# menosic/music/settings/models.py
from django.contrib.auth.models import User
from django.db import models


class MusicSettings(models.Model):
    ORDERING_CHOICES = (
        ('sortname', 'By Artist (sortname)'),
        ('name', 'By Artist (full)'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, db_index=True)
    ordering = models.CharField(
        max_length=20,
        choices=ORDERING_CHOICES,
        default=ORDERING_CHOICES[0][0]
    )

    @classmethod
    def get(cls, user):
        if type(user) == type(User):
            pk = user.pk
        else:
            pk = user
            try:
                user = User.objects.get(pk=pk)
            except User.DoesNotExist:
                return None
        try:
            obj = cls.objects.get(user__pk=pk)
        except cls.DoesNotExist:
            obj = cls(user=user)
        return obj

menosic/music/settings/forms.py
# menosic/music/settings/forms
from django import forms

from .models import MusicSettings


class MusicSettingsForm(forms.ModelForm):
    class Meta:
        model = MusicSettings
        fields = ['ordering',]

menosic/music/settings/views/settings.py
# menosic/music/settings/views/settings.py
from django.urls import reverse
from django.http import Http404
from django.views.generic import UpdateView

from .. import forms


class MusicSettingsView(UpdateView):
    form_class = forms.MusicSettingsForm
    template_name = "music/settings/settings.html"

    def get_object(self, **kwargs):
        if hasattr(self, "request") and \
           hasattr(self.request, "user") and \
           hasattr(self.request.user, "settings"):
            obj = self.request.user.settings
            if not obj.pk:
                obj.save()
            return obj
        else:
            raise Http404

    def get_success_url(self):
        return reverse("music:home")

menosic/music/templates/music/album_detail.html
<a href="{{ album.artist.get_absolute_url }}">{{ album.artist.name }}</a> / {{ album.title }}

<div class="album">
  {% if album.cover %}
  <div class="album-cover">
    <img src="{% url 'music:cover' album.pk %}">
  </div>
  {% endif %}
  <h2>{{ album.title }}</h2>
</div>
<p><a class="to_playlist" href="{% url 'music:add_album' album.id %}"><i class="glyphicon glyphicon-plus"></i><i class="glyphicon glyphicon-th-list"></i> add whole album to playlist</a></p>


<table class="table table-hover">
<thead>
    <tr>
        <th>Add</th>
        <th>#</th>
        <th>Title</th>
        <th>Duration</th>
    </tr>
</thead>
<tbody>
{% for track in album.track_set.all %}
    {% ifchanged track.discnumber %}
    <tr>
        <th colspan="4">Disc {{ track.discnumber }}</th>
    </tr>
    {% endifchanged %}
    <tr>
        <td><a class="to_playlist add_to_playlist" href="{% url 'music:add_track' track.id %}"><i class="glyphicon glyphicon-plus"></i></a></td>
        <td>{{ track.tracknumber }}</td>
        <td><a class="to_playlist" href="{% url 'music:play_album_track' track.id %}">{{ track.title }}</a>
        <td>{{ track.duration }}</td>
    </tr>
{% endfor %}
</tbody>
</table>

menosic/music/templates/music/artist_detail.html
{{ artist.name }}

<h2>{{ artist.name }}</h2>

<ul class="related">
{% for artist in artist.related_artists %}
    <li><a href="{{ artist.get_absolute_url }}">{{ artist }}</a>, </li>
{% endfor %}
</ul>

{% with albums=artist.album_set.all %}
  {% if albums.count > 1 %}<a href="{% url "music:random_album" artist.pk %}"><i class="glyphicon glyphicon-random"></i></a>{% endif %}
  <ul id="album_list">
  {% for album in albums %}
  <li class="{% for album_type in album.album_types %}albumtype-{{ album_type }} {% endfor %}"><a href="{{ album.get_absolute_url }}">{% if album.year %}{{ album.year }} - {% endif %}{{ album.title }}
          {% if album.album_types %}({% for album_type in album.album_types %}{{ album_type }}{% if not forloop.last %}, {% endif %}{% endfor %}){% endif %}
      </a></li>
  {% empty %}
      <li>No albums for {{ artist.name }}.</li>
  {% endfor %}
  </ul>
{% endwith %}

{% if artist.related_albums %}
    <h3>Related Albums</h3>

    <ul id="album_list">
    {% for album in artist.related_albums %}
    <li class="{% for album_type in album.album_types %}albumtype-{{ album_type }} {% endfor %}"><a href="{{ album.get_absolute_url }}">{% if album.year %}{{ album.year }} - {% endif %}{{ album.artist }} - {{ album.title }}
          {% if album.album_types %}({% for album_type in album.album_types %}{{ album_type }}{% if not forloop.last %}, {% endif %}{% endfor %}){% endif %}
    </a></li>
    {% endfor %}
    </ul>
{% endif %}

menosic/music/templates/music/artist_list.html
{% extends 'base.html' %}

{% block artists %}

  <h2>Artists</h2>
  <ul class="nav nav-sidebar">
    {% for artist in object_list %}
    {% ifchanged %}</ul>{{ artist.sortname.0 }}<ul>{% endifchanged %}
    <li><a href="{{ artist.get_absolute_url }}">{{ artist.name }}</a></li>
    {% endfor %}
  </ul>

{% endblock artists %}

menosic/music/templates/music/browse.html
{% for crumb in crumbs %}
    {% if forloop.last %}
    {{ crumb.name }}
    {% else %}
    <a href="{{ crumb.get_absolute_url }}">{{ crumb.name }}</a> /
    {% endif %}
{% endfor %}

<div class="album">
  <h2>{{ current.name }}</h2>
</div>
<p><a class="to_playlist" href="{% url 'music:add_album_files' current.collection.id current.encoded_path %}"><i class="glyphicon glyphicon-plus"></i><i class="glyphicon glyphicon-th-list"></i> add whole album to playlist</a></p>

<ul>
{% for item in dirs %}
    <li><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></li>
{% endfor %}
</ul>

{% if files %}
<table class="table table-hover">
<thead>
    <tr>
        <th>Add</th>
        <th>#</th>
        <th>Title</th>
        <th>Duration</th>
    </tr>
</thead>
<tbody>
{% for track in files %}
    <tr>
        <td><a class="to_playlist add_to_playlist" href="{% url 'music:add_file' track.collection.id track.encoded_path %}"><i class="glyphicon glyphicon-plus"></i></a></td>
        <td>{{ track.tag.tracknumber }}</td>
        <td><a class="to_playlist" href="{{ track.get_absolute_url }}">{{ track.tag.title }}</a>
        <td>{{ track.tag.duration }}</td>
    </tr>
{% endfor %}
</tbody>
</table>
{% endif %}

menosic/music/templates/music/country_detail.html
<h2>{{ country.name }}</h2>

<ul id="artist_list">
{% for artist in country.artists %}
<li><a href="{{ artist.get_absolute_url }}">{{ artist.name }}</a></li>
{% empty %}
  <li>No artist for {{ country.name }}.</li>
{% endfor %}
</ul>

menosic/music/templates/music/genre_detail.html
<h2>{{ genre.name }}</h2>

<ul id="artist_list">
{% for artist in genre.artists %}
<li><a href="{{ artist.get_absolute_url }}">{{ artist.name }}</a></li>
{% empty %}
  <li>No artist for {{ genre.name }}.</li>
{% endfor %}
</ul>

menosic/music/templates/music/last_played.html
<h3>Last played</h3>

{% for last_played in object_list %}
<p><b>{{ last_played.user }}</b></p>
<div class="last-played-item">
  <div class="last-played-info">
    <a href="{{ last_played.track.album.get_absolute_url }}" class="to_content">
    {{ last_played.track.artist }}<br/>
    {{ last_played.track.title }}
    </a>
  </div>
  {% if last_played.track.album.cover %}
    <div class="album-cover">
      <img src="{% url 'music:cover' last_played.track.album.pk %}">
    </div>
  {% endif %}
  <p class="clear">{{ last_played.minutes_ago }} minutes ago</p>
</div>
{% endfor %}

menosic/music/templates/music/new_album_list.html
<h1>New albums</h1>

{% if not new_albums %}
<p>No new albums found!</p>
{% else %}
<div id="new-albums">
  {% for album in new_albums %}
  <div class="new-album-item">
    <div class="thumbnail">
      <a href="{{ album.get_absolute_url }}">
        <img src="{% url 'music:cover' album.pk %}">
      </a>
    </div>
    <div class="caption">
      <h3><a href="{{ album.get_absolute_url }}">{{ album.title }} ({{ album.year|default:"????" }})</a></h3>
      {% for artist in album.artists.all %}
      <h4><a href="{{ artist.get_absolute_url }}">{{ artist.name }}</a></h4>
      {% endfor %}
      <p><a class="to_playlist" href="{% url 'music:add_album' album.id %}"><i class="glyphicon glyphicon-plus"></i><i class="glyphicon glyphicon-th-list"></i></a></p>
    </div>
  </div>
  {% endfor %}
</div>
{% if is_paginated %}
 <div class="pagination">
     <span class="page-links">
         {% if page_obj.has_previous %}
             <a href="{% url "music:new_albums" %}?page={{ page_obj.previous_page_number }}"><i class="glyphicon glyphicon-backward"></i></a>
         {% endif %}
         <span class="page-current">
             Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
         </span>
         {% if page_obj.has_next %}
             <a href="{% url "music:new_albums" %}?page={{ page_obj.next_page_number }}"><i class="glyphicon glyphicon-forward"></i></a>
         {% endif %}
     </span>
 </div>
{% endif %}
{% endif %}

menosic/music/templates/music/playlist.html
<table class="table table-hover">
<thead>
    <tr>
        <th id='actions'></th>
        <th>Title</th>
        <th>Artist</th>
        <th>Album</th>
        <th>Duration</th>
    </tr>
</thead>
<tbody>
{% for pt in playlist.tracks %}
    <tr id="{{ pt.identifier }}" {% if pt.identifier == current %}class="playing"{% endif %}>
        <td>
            <a class="to_playlist" href="{% url 'music:edit_playlist_track' pt.id 'remove' %}"><i class="glyphicon glyphicon-trash"></i></a>
            <a class="to_playlist" href="{% url 'music:edit_playlist_track' pt.id 'up' %}"><i class="glyphicon glyphicon-menu-up"></i></a>
            <a class="to_playlist" href="{% url 'music:edit_playlist_track' pt.id 'down' %}"><i class="glyphicon glyphicon-menu-down"></i></a>
        </td>
        <td><a class="to_player" mp3="{{ pt.track.get_mp3_url }}" ogg="{{ pt.track.get_ogg_url }}">{{ pt.track.title }}</a></td>
        <td>{{ pt.track.artist }}</td>
        <td>{{ pt.track.album.title }}</td>
        <td>{{ pt.track.duration }}</td>
    </tr>
{% endfor %}
</tbody>
</table>

menosic/music/templates/music/track_detail.html
<a href="{{ track.album.artists.all.0.get_absolute_url }}">{{ track.album.artists.all.0.name }}</a> / <a href="{{ track.album.get_absolute_url }}">{{ track.album.title }}</a> / {{ track.title }}

<h1>{{ track.title }}</h1>
<ul>
    <li>Filetype: {{ track.filetype }}</li>
    <li>Bitrate: {{ track.bitrate }}</li>
</ul>
<audio controls>
    <source src="{{ track.get_file_url }}" type="audio/mpeg">
</audio>